[package]
name = "linimasa-ai-api"
version = "0.1.0"
edition = "2024"

[dependencies]
ollama-rs = { version = "0.3.1", features = ["stream"] }
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
